apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-app
  labels:
    app: nginx
    type: front-end
spec:
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        type: front-end
    spec:
      containers:
      - name: nginx
        image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: front-end